### User register
POST https://blogapp-backend-v72w.onrender.com/user-api/users
Content-Type: application/json

{
    "firstName":"pavanika",
    "lastName":"minukuri",
    "email":"pavanika.user@example.com",
    "password":"User@12345",
    "profileImageUrl":"https://example.com.avatars.author.png"
}

### User Login
POST https://blogapp-backend-v72w.onrender.com/common-api/login
Content-Type: application/json

{
  "email": "pavanika.user@example.com",
  "password": "User@12345"
 
}

### read all articles by user
GET https://blogapp-backend-v72w.onrender.com/user-api/articles

### add comment to an article by user
PUT https://blogapp-backend-v72w.onrender.com/user-api/articles
Content-Type: application/json

{
    "user":"69aedcfde1032a43f31faec0",
    "articleId":"69aedd86e1032a43f31faecc",
    "comment":"Good article."
}






### Author register
POST https://blogapp-backend-v72w.onrender.com/author-api/users
Content-Type: application/json

{
    "firstName":"varshith",
    "lastName":"inupamula",
    "email":"varshith.author@example.com",
    "password":"Author@12345",
    "profileImageUrl":"https://example.com.avatars.author.png"
}

### Author Login
POST https://blogapp-backend-v72w.onrender.com/common-api/login
Content-Type: application/json

{
    "email":"varshith.author@example.com",
    "password":"Author@12345"
}

###  create articles (AUTHOR)
POST https://blogapp-backend-v72w.onrender.com/author-api/articles
Content-Type: application/json

{
    "author":"69aedd3fe1032a43f31faec4",
    "title":"Article 3",
    "category":"SQL",
    "content":"content of article 3"
}


### Read articles of author
GET https://blogapp-backend-v72w.onrender.com/author-api/articles/69aedd3fe1032a43f31faec4


###  update articles
PUT https://blogapp-backend-v72w.onrender.com/author-api/articles
Content-Type: application/json

{
    "author":"69aedd3fe1032a43f31faec4",
    "articleId":"69aedd86e1032a43f31faecc",
    "title":"Article 2",
    "category":"programming",
    "content":"content of article 2 updated"
}

### delete an article
PATCH  https://blogapp-backend-v72w.onrender.com/author-api/articles/69aedd50e1032a43f31faec7/status
Content-Type: application/json

{
    "isArticleActive":false
}






### read all articles by admin
GET https://blogapp-backend-v72w.onrender.com/admin-api/articles


### block user roles
POST https://blogapp-backend-v72w.onrender.com/admin-api/block-user
Content-Type: application/json

{
    "userId":"698dfcaa90cb51bc33da882b",
    "role":"author"
}

### unblock user roles
POST https://blogapp-backend-v72w.onrender.com/admin-api/unblock-user
Content-Type: application/json

{
    "userId":"69896dbf9342acaad0d14923",
    "role":"author"
}


### change password
PUT https://blogapp-backend-v72w.onrender.com/common-api/change-password
Content-Type: application/json

{
    "email":"pavanika.user@example.com",
    "currentPassword":"User@12345",
    "newPassword":"pavu15"
}



### logout
POST  https://blogapp-backend-v72w.onrender.com/common-api/logout


### Test res
GET https://blogapp-backend-v72w.onrender.com/test
